Algoritmo "Entrada e saida de Dados"

// Descrição   : "Entrada e saida de Dados"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreval("Digite o seu nome")
    Leia(nome)
    Escreval ("Digite a sua nota")
    Leia(nota)
    
    escreval("O nome digitado foi",nome)
    escreval("A nota digitada foi",nota)

Fimalgoritmo